[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
prereqs = "A8fUgq5NcEryu3TwdTWeVnxyYA7cHgmwfrKwveSpi4rz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/conel0826/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
